### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Ruud-cb** [swimlane/mongtype#12]
Just doing it as documented:

Making use of mongoDB's free cluster.

```
export class BaseRepository<T> extends MongoRepository<T> {
    constructor() {
        const dbc = new DatabaseClient();
        dbc.connect('mongodb+srv://<username>:<password>@clusterx-0c6u9.azure.mongodb.net/test'); 
        super(dbc);
    }



    /**
     * Create a document of type T
     *
     * @param {T} document
     * @returns {Promise<T>}
     * @memberof MongoRepository
     */
    public async create(document) {
        if (typeof document.clearForDb === 'function') {
            console.log("clearForDb");
            document.clearForDb()
        }
        console.log("BaseRepo - Insert item");
        try {
            return super.create(document);
        } catch (error) {
            console.log(error);
        }
    }
```

after calling create it throws an error:

(node:1828) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at Promise (c:\Users\Ruud\source\repos\KasperStrats\node_modules\mongtype\dist\Repository.js:241:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Also 2 warnings:

(node:1828) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:1828) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

Seems that something is not going correctly with filling the 'options' property.

When I remove `+srv` from the connection string, it doesn't throw this particular error, but inserting never seems to complete, the await waits forever.

Fixing the first warning by adding `useInifiedTopolgy` to the `connect` options parameters doesn't seem to help. Running on the latest version of mongtype.

**Comment by shaunburdick** [comment]
`this.options.name` is trying to get the name of the collection however it doesn't seem to be set in your example. You need to use the `@Collection({ name: '...'})` decorator

**Comment by Ruud-cb** [comment]
*bangs head against the wall* 

thanks..
Was confusing because in the ReadMe it shows under "With DI", I only followed "Without DI" and wrote the repository myself instead of looking at the "With DI" section...

**Comment by shaunburdick** [comment]
I'm glad that worked out. To me it says we need a better error message and handling of this case. I'll take a look and see about updating it.
