### ISSUE TITLE
Mongtype with inversify docs not found

### ISSUE THREAD

**Issue by VictorMonte** [swimlane/mongtype#14]
Hi guys,

I'm having a hard time to use mongtype with Inversify.
Is this possible?
Is there any documentation about it?

Sorry to bother, I tried one my own, but it didnt work.

**Comment by shaunburdick** [comment]
We use inversify internally with projects that use Mongtype.
I don't have any documentation for you as I don't want to be opinionated about something that doesn't directly align with the project 😞 
If you can provide more information I might be able to help you in this ticket?
