### ISSUE TITLE
What if connection is lost

### ISSUE THREAD

**Issue by mustafaekim** [swimlane/mongtype#3]
Hi,

Your Database class sets up a connection and keep it within a promise, which you call from a repository. What happens when the connection is lost? Does it re-connect automatically?

The code below does not seem to me like it re-tries to open a connection that may be lost:

```ts
  public getConnection(): Promise<Db> {
    if (!this.db) {
      try {
        this.db = MongoClient.connect(this.uri);
        console.log(`Mongo: Connection opened: ${this.uri}`);
      } catch(e) {
        console.error('Mongo: Connection error', e);
      }
    }
    return this.db;
  }
```

Sorry if that is a stupid question, because I am a new comer to the NodeJS environment, I dont easily get how things are resolved

**Comment by amcdnl** [comment]
There is no auto-reconnect. Good call, I'll add that.
