### ISSUE TITLE
What tool do you use for dependency injection?

### ISSUE THREAD

**Issue by toverux** [swimlane/mongtype#8]
Hello,

Sorry for the silly question and the noise.
You mention dependency injection (a pattern that is too rare in Node.js) and you are using an `@Injectable` decorator commonly used in Angular. Inversify uses `@injectable`, though. Maybe that's just an example...
I'd like to know what library do you use/recommend for server-side DI?

Thanks, and again, sorry for this off-topic question :)

**Comment by shaunburdick** [comment]
We use [InversifyJS](https://github.com/inversify/InversifyJS) for an internal project that uses this library.
